/*
 * Copyright (c) Siemens AG 2015 ALL RIGHTS RESERVED.
 *
 * R8  
 * 
 */

package com.home.problem;

/**
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * Answer: 4613732
 * 
 */
public class Problem2
{
    public static void main(String[] args)
    {
        long a=1;
        long b = 2;
        long sum = 2;
        while(true)
        {
            long temp = b;
            b += a;
            a = temp;
            if (b > 4000000)
                break;
            if (b % 2 == 0)
                sum += b;
        }

        System.out.println("Sum is : =" + sum);
    }
}


/*
 * Copyright (c) Siemens AG 2015 ALL RIGHTS RESERVED
 *
 * R8
 */
